language: python

install:
  - |
    eval "$(pyenv init -)"
    env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install --skip-existing $PYVER
    pyenv global $PYVER
    pyenv shell $PYVER
    pip install -U pip setuptools wheel
    pip install .

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=python3.6 PYVER=3.6.2
    - os: osx
      language: generic
      env: PYTHON=python2.7 PYVER=2.7.13

script: $PYTHON setup.py test
